---
title: "BART"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(BART)
library(tidyverse)
```

## example

```{r}
##simulate data (example from Friedman MARS paper)
f = function(x){
10*sin(pi*x[,1]*x[,2]) + 20*(x[,3]-.5)^2+10*x[,4]+5*x[,5]
}
sigma = 1.0 #y = f(x) + sigma*z , z~N(0,1)
n = 100 #number of observations
set.seed(99)
x=matrix(runif(n*10),n,10) #10 variables, only first 5 matter
Ey = f(x)
y=Ey+sigma*rnorm(n)
lmFit = lm(y~.,data.frame(x,y)) #compare lm fit to BART later
##test BART with token run to ensure installation works
set.seed(99)
bartFit = wbart(x,y,nskip=5,ndpost=5)
## Not run:
##run BART
set.seed(99)
bartFit = wbart(x,y)
##compare BART fit to linear matter and truth = Ey
fitmat = cbind(y,Ey,lmFit$fitted,bartFit$yhat.train.mean)
colnames(fitmat) = c('y','Ey','lm','bart')
print(cor(fitmat))
## End(Not run)
plot(y)+
  points(Ey,col="red")+
  points(lmFit$fitted,col="blue")+
  points(bartFit$yhat.train.mean,col="yellow")
```

```{r}
## load the advanced lung cancer example
    data(lung)
    group <- -which(is.na(lung[ , 7])) ## remove missing row for ph.karno
    times <- lung[group, 2]   ##lung$time
    delta <- lung[group, 3]-1 ##lung$status: 1=censored, 2=dead
                              ##delta: 0=censored, 1=dead
    ## this study reports time in days rather than months like other studies
    ## coarsening from days to months will reduce the computational burden
    times <- ceiling(times/30)
    summary(times)
    table(delta)
    x.train <- as.matrix(lung[group, c(4, 5, 7)]) ## matrix of observed covariates
## lung$age:
## lung$sex:
## lung$ph.karno:
##
##Age in years
##Male=1 Female=2
##Karnofsky performance score (dead=0:normal=100:by=10)
##rated by physician
dimnames(x.train)[[2]] <- c('age(yr)', 'M(1):F(2)', 'ph.karno(0:100:10)')
summary(x.train[ , 1])
table(x.train[ , 2])
table(x.train[ , 3])
x.test <- matrix(nrow=84, ncol=3) ## matrix of covariate scenarios
dimnames(x.test)[[2]] <- dimnames(x.train)[[2]]
i <- 1
for(age in 5*(9:15)) for(sex in 1:2) for(ph.karno in 10*(5:10)) {
    x.test[i, ] <- c(age, sex, ph.karno)
    i <- i+1 }
## this x.test is relatively small, but often you will want to
## predict for a large x.test matrix which may cause problems
## due to consumption of RAM so we can predict separately
## mcparallel/mccollect do not exist on windows
if(.Platform$OS.type=='unix') {
##test BART with token run to ensure installation works
set.seed(99)
post <- surv.bart(x.train=x.train, times=times, delta=delta, nskip=5, ndpost=5, keepevery=1)
    pre <- surv.pre.bart(x.train=x.train, times=times, delta=delta, x.test=x.test)
    pred <- predict(post, pre$tx.test)
    ##pred. <- surv.pwbart(pre$tx.test, post$treedraws, post$binaryOffset)
}
## Not run:
## run one long MCMC chain in one process
set.seed(99)
post <- surv.bart(x.train=x.train, times=times, delta=delta)
## run "mc.cores" number of shorter MCMC chains in parallel processes
## post <- mc.surv.bart(x.train=x.train, times=times, delta=delta,
##                      mc.cores=5, seed=99)
pre <- surv.pre.bart(x.train=x.train, times=times, delta=delta, x.test=x.test)
pred <- predict(post, pre$tx.test)
## let's look at some survival curves
## first, a younger group with a healthier KPS
## age 50 with KPS=90: males and females
## males: row 17, females: row 23
x.test[c(17, 23), ]
low.risk.males <- 16*post$K+1:post$K ## K=unique times including censoring
low.risk.females <- 22*post$K+1:post$K
plot(post$times, pred$surv.test.mean[low.risk.males], type='s', col='blue',
     main='Age 50 with KPS=90', xlab='t', ylab='S(t)', ylim=c(0, 1))
points(post$times, pred$surv.test.mean[low.risk.females], type='s', col='red')
## End(Not run)
```

## Population

```{r}
population_data=read.csv("finite_pop.csv")
survey_data=read.csv("selected_data.csv")
sub_cohort_data=read.csv("selected_sub_cohort.csv")

```

## survey sample

```{r}

```

## sub cohort sample

```{r}
set.seed(1)
sub_cohort_data_clean=drop_na(sub_cohort_data)
bartFit = gbart(sub_cohort_data_clean[,7:18],sub_cohort_data_clean$y,type = 'pbart',x.test = survey_data[,7:18])
## method one
set.seed(1)
post=gbart(sub_cohort_data_clean[,7:18],sub_cohort_data_clean$y,type = 'pbart')
bartFit$prob.train.mean
bartFit$prob.test.mean
## method two
set.seed(1)
pred=predict(post, survey_data[,7:18])
pred$prob.test.mean


```


```{r}
srclib <<- "/Applications/srclib/R"
source(file.path(srclib, "init.R", fsep=.Platform$file.sep))

bbdesign(name = "bbdesign")

ds[which(ds$IMPL_==1),]
selected_data=read_csv("./selected_data.csv")
finite_pop=read_csv("./finite_pop.csv")
unique(selected_data[,3:4])
```

