---
title: "simulation"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## generate finite population

```{r}
set.seed(1)
strata=5
n_strata=c(200,150,100,50,25)
number_of_household=rexp(789,rate = 1/200)
number_of_household=round(number_of_household[which(number_of_household<400 & number_of_household>50)])
plot(density(number_of_household))

sum_number_of_household=sum(number_of_household)

set.seed(1)
individual_number=rpois(sum_number_of_household,1)+1
set.seed(1)
plot(density(rpois(sum_number_of_household,1)))

individual=NULL
i=1
for(i in 1:sum_number_of_household){
  individual=c(individual,1:individual_number[i])
}

household_1=NULL
i=1
for(i in 1:sum(n_strata)){
  household_1=c(household_1,1:number_of_household[i])
  }

household=NULL
i=1
for(i in 1:sum_number_of_household){
  household=c(household,rep(household_1[i],individual_number[i]))
}

enumeration_1=NULL
i=1
for(i in 1:strata){
  enumeration_1=c(enumeration_1,1:n_strata[i])
}

enumeration_2=NULL
i=1
for(i in 1:sum(n_strata)){
  enumeration_2=c(enumeration_2,rep(enumeration_1[i],number_of_household[i]))
}

enumeration=NULL
i=1
for(i in 1:sum_number_of_household){
  enumeration=c(enumeration,rep(enumeration_2[i],individual_number[i]))
}

stype_1=NULL
for(i in 1:strata){
  stype_1=c(stype_1,rep(i,c(200,150,100,50,25)[i]))
}

stype_2=NULL
for(i in 1:sum(n_strata)){
  stype_2=c(stype_2,rep(stype_1[i],number_of_household[i]))
}

stype=NULL
for(i in 1:sum_number_of_household){
  stype=c(stype,rep(stype_2[i],individual_number[i]))
}

x_1=rep(NA,length(stype))
x_2=rep(NA,length(stype))
x_3=rep(NA,length(stype))
x_4=rep(NA,length(stype))
x_5=rep(NA,length(stype))

z_1=rep(NA,length(stype))
z_2=rep(NA,length(stype))
z_3=rep(NA,length(stype))
z_4=rep(NA,length(stype))
z_5=rep(NA,length(stype))

id=1:length(stype)
finite_pop=as.data.frame(cbind(id,stype,enumeration,household,individual,x_1,x_2,x_3,x_4,x_5,z_1,z_2,z_3,z_4,z_5))

set.seed(1)
mean_strata_1_norm=rnorm(n_strata[1],2,0.5)
set.seed(1)
mean_strata_1_bino=runif(n_strata[1],0,0.2)
for(i in 1:n_strata[1]){
  set.seed(1)
finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]$x_1=round(rnorm(nrow(finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]),mean_strata_1_norm[i],2),2)
  set.seed(1)
finite_pop[which(finite_pop$stype==1 &
finite_pop$enumeration==i),]$z_1=rbinom(nrow(finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_1_bino[i])

  set.seed(2)
finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]$x_2=round(rnorm(nrow(finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]),mean_strata_1_norm[i]+0.2,1),2)
  set.seed(2)
finite_pop[which(finite_pop$stype==1 &
finite_pop$enumeration==i),]$z_2=rbinom(nrow(finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_1_bino[i]+0.02)

  set.seed(3)
finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]$x_3=round(rnorm(nrow(finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]),mean_strata_1_norm[i]+0.4,3),1)
  set.seed(3)
finite_pop[which(finite_pop$stype==1 & 
finite_pop$enumeration==i),]$z_3=rbinom(nrow(finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_1_bino[i]+0.04)

  set.seed(4)
finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]$x_4=round(rnorm(nrow(finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]),mean_strata_1_norm[i]+0.6,4),1)
  set.seed(4)
finite_pop[which(finite_pop$stype==1 & 
finite_pop$enumeration==i),]$z_4=rbinom(nrow(finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_1_bino[i]+0.06)

  set.seed(5)
finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]$x_5=round(rnorm(nrow(finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]),mean_strata_1_norm[i]+0.8,5),1)
  set.seed(5)
finite_pop[which(finite_pop$stype==1 & 
finite_pop$enumeration==i),]$z_5=rbinom(nrow(finite_pop[which(finite_pop$stype==1 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_1_bino[i]+0.08)
}

set.seed(2)
mean_strata_2_norm=rnorm(n_strata[2],4,1)
set.seed(2)
mean_strata_2_bino=runif(n_strata[2],0,0.4)
for(i in 1:n_strata[2]){
  set.seed(1)
finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]$x_1=round(rnorm(nrow(finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]),mean_strata_2_norm[i],2),2)
  set.seed(1)
finite_pop[which(finite_pop$stype==2 & 
finite_pop$enumeration==i),]$z_1=rbinom(nrow(finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_2_bino[i])

  set.seed(2)
finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]$x_2=round(rnorm(nrow(finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]),mean_strata_2_norm[i]+0.2,1),2)
  set.seed(2)
finite_pop[which(finite_pop$stype==2 &
finite_pop$enumeration==i),]$z_2=rbinom(nrow(finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_2_bino[i]+0.02)

  set.seed(3)
finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]$x_3=round(rnorm(nrow(finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]),mean_strata_2_norm[i]+0.4,3),1)
  set.seed(3)
finite_pop[which(finite_pop$stype==2 & 
finite_pop$enumeration==i),]$z_3=rbinom(nrow(finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_2_bino[i]+0.04)

  set.seed(4)
finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]$x_4=round(rnorm(nrow(finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]),mean_strata_2_norm[i]+0.6,4),1)
  set.seed(4)
finite_pop[which(finite_pop$stype==2 & 
finite_pop$enumeration==i),]$z_4=rbinom(nrow(finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_2_bino[i]+0.06)

  set.seed(5)
finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]$x_5=round(rnorm(nrow(finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]),mean_strata_2_norm[i]+0.8,5),1)
  set.seed(5)
finite_pop[which(finite_pop$stype==2 & 
finite_pop$enumeration==i),]$z_5=rbinom(nrow(finite_pop[which(finite_pop$stype==2 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_2_bino[i]+0.08)
}

set.seed(3)
mean_strata_3_norm=rnorm(n_strata[3],6,2)
set.seed(3)
mean_strata_3_bino=runif(n_strata[3],0,0.6)
for(i in 1:n_strata[3]){
  set.seed(1)
finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]$x_1=round(rnorm(nrow(finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]),mean_strata_3_norm[i],2),2)
  set.seed(1)
finite_pop[which(finite_pop$stype==3 &
finite_pop$enumeration==i),]$z_1=rbinom(nrow(finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_3_bino[i])

  set.seed(2)
finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]$x_2=round(rnorm(nrow(finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]),mean_strata_3_norm[i]+0.2,1),2)
  set.seed(2)
finite_pop[which(finite_pop$stype==3 &
finite_pop$enumeration==i),]$z_2=rbinom(nrow(finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_3_bino[i]+0.02)

  set.seed(3)
finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]$x_3=round(rnorm(nrow(finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]),mean_strata_3_norm[i]+0.4,3),1)
  set.seed(3)
finite_pop[which(finite_pop$stype==3 &
finite_pop$enumeration==i),]$z_3=rbinom(nrow(finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_3_bino[i]+0.04)

  set.seed(4)
finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]$x_4=round(rnorm(nrow(finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]),mean_strata_3_norm[i]+0.6,4),1)
  set.seed(4)
finite_pop[which(finite_pop$stype==3 & 
finite_pop$enumeration==i),]$z_4=rbinom(nrow(finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_3_bino[i]+0.06)

  set.seed(5)
finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]$x_5=round(rnorm(nrow(finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]),mean_strata_3_norm[i]+0.8,5),1)
  set.seed(5)
finite_pop[which(finite_pop$stype==3 & 
finite_pop$enumeration==i),]$z_5=rbinom(nrow(finite_pop[which(finite_pop$stype==3 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_3_bino[i]+0.08)
}

set.seed(4)
mean_strata_4_norm=rnorm(n_strata[4],7,2)
set.seed(4)
mean_strata_4_bino=runif(n_strata[4],0,0.8)
for(i in 1:n_strata[4]){
  set.seed(1)
finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]$x_1=round(rnorm(nrow(finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]),mean_strata_4_norm[i],2),2)
  set.seed(1)
finite_pop[which(finite_pop$stype==4 & 
finite_pop$enumeration==i),]$z_1=rbinom(nrow(finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_4_bino[i])

  set.seed(2)
finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]$x_2=round(rnorm(nrow(finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]),mean_strata_4_norm[i]+0.2,1),2)
  set.seed(2)
finite_pop[which(finite_pop$stype==4 &
finite_pop$enumeration==i),]$z_2=rbinom(nrow(finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_4_bino[i]+0.02)

  set.seed(3)
finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]$x_3=round(rnorm(nrow(finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]),mean_strata_4_norm[i]+0.4,3),1)
  set.seed(3)
finite_pop[which(finite_pop$stype==4 & 
finite_pop$enumeration==i),]$z_3=rbinom(nrow(finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_4_bino[i]+0.04)

  set.seed(4)
finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]$x_4=round(rnorm(nrow(finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]),mean_strata_4_norm[i]+0.6,4),1)
  set.seed(4)
finite_pop[which(finite_pop$stype==4 & 
finite_pop$enumeration==i),]$z_4=rbinom(nrow(finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_4_bino[i]+0.06)

  set.seed(5)
finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]$x_5=round(rnorm(nrow(finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]),mean_strata_4_norm[i]+0.8,5),1)
  set.seed(5)
finite_pop[which(finite_pop$stype==4 & 
finite_pop$enumeration==i),]$z_5=rbinom(nrow(finite_pop[which(finite_pop$stype==4 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_4_bino[i]+0.08)
}

set.seed(5)
mean_strata_5_norm=rnorm(n_strata[5],9,2)
set.seed(5)
mean_strata_5_bino=runif(n_strata[5],0,0.9)
for(i in 1:n_strata[5]){
  set.seed(1)
finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]$x_1=round(rnorm(nrow(finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]),mean_strata_5_norm[i],2),2)
  set.seed(1)
finite_pop[which(finite_pop$stype==5 & 
finite_pop$enumeration==i),]$z_1=rbinom(nrow(finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_5_bino[i])

  set.seed(2)
finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]$x_2=round(rnorm(nrow(finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]),mean_strata_5_norm[i]+0.2,1),2)
  set.seed(2)
finite_pop[which(finite_pop$stype==5 & 
finite_pop$enumeration==i),]$z_2=rbinom(nrow(finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_5_bino[i]+0.02)

  set.seed(3)
finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]$x_3=round(rnorm(nrow(finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]),mean_strata_5_norm[i]+0.4,3),1)
  set.seed(3)
finite_pop[which(finite_pop$stype==5 & 
finite_pop$enumeration==i),]$z_3=rbinom(nrow(finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_5_bino[i]+0.04)

  set.seed(4)
finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]$x_4=round(rnorm(nrow(finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]),mean_strata_5_norm[i]+0.6,4),1)
  set.seed(4)
finite_pop[which(finite_pop$stype==5 & 
finite_pop$enumeration==i),]$z_4=rbinom(nrow(finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_5_bino[i]+0.06)

  set.seed(5)
finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]$x_5=round(rnorm(nrow(finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]),mean_strata_5_norm[i]+0.8,5),1)
  set.seed(5)
finite_pop[which(finite_pop$stype==5 & 
finite_pop$enumeration==i),]$z_5=rbinom(nrow(finite_pop[which(finite_pop$stype==5 & finite_pop$enumeration==i),]),size = 1, prob = mean_strata_5_bino[i]+0.08)
}

i=1
j=1
num_house=NULL
for(i in 1:strata){
  for(j in 1:n_strata[i]){
    num_house=c(num_house,rep(tail(finite_pop[which(finite_pop$stype==i & finite_pop$enumeration==j),],1)$household,nrow(finite_pop[which(finite_pop$stype==i &finite_pop$enumeration==j),])))
  }
}


i=1
j=1
m=1
j=0
num_indiv=NULL
for(i in 1:strata){
  for(j in 1:n_strata[i]){
    for(m in 1:tail(finite_pop[which(finite_pop$stype==i & finite_pop$enumeration==j),],1)$household){
       num_indiv=c(num_indiv,rep(tail(finite_pop[which(finite_pop$stype==i & finite_pop$enumeration==j & finite_pop$household==m),],1)$individual,nrow(finite_pop[which(finite_pop$stype==i &finite_pop$enumeration==j & finite_pop$household==m),])))
    }
  }
}

set.seed(1)
random_inter_ea=rnorm(sum(n_strata),5,5) %>% 
  as.data.frame() %>% 
  mutate(
    enumeration=c(1:n_strata[1],1:n_strata[2],1:n_strata[3],1:n_strata[4],1:n_strata[5]),
    stype=c(rep(1,n_strata[1]),rep(2,n_strata[2]),rep(3,n_strata[3]),rep(4,n_strata[4]),rep(5,n_strata[5]))
  )

colnames(random_inter_ea)=c("random_inter_ea","enumeration","stype")
finite_pop=left_join(finite_pop, random_inter_ea, by = c("enumeration","stype"))

finite_pop=finite_pop %>% 
  mutate(
    num_house=num_house,
    num_indiv=num_indiv,
    x_1_norm=round(scale(x_1),2),
    x_2_norm=round(scale(x_2),2),
    x_3_norm=round(scale(x_3),2),
    x_4_norm=round(scale(x_4),2),
    x_5_norm=round(scale(x_5),2),
    z=random_inter_ea-6+0.38*x_1-4*x_2+0.3*x_4-3*x_5+1.5*z_1-1.4*z_3-5*z_4+2*stype+0.03*num_house+1.2*num_indiv,
    pr=1/(1+exp(-z)),
    y = rbinom(length(stype),1,pr) 
  )

sum(finite_pop$y)/length(stype)


write.csv(finite_pop,"finite_pop")
```

## Do a sampling to select a survey sample

```{r}
## select mh EAs  from  each  stratum
sizes=number_of_household
strat=c(rep(1,n_strata[1]),rep(2,n_strata[2]),rep(3,n_strata[3]),rep(4,n_strata[4]),rep(5,n_strata[5]))
n=c(50,30,20,15,10)
set.seed(1)
selected_ea=ppssstrat(sizes,strat,n)
##for stype1
selected_1=selected_ea[which(selected_ea<n_strata[1]+1)]
##for stype2
selected_2=selected_ea[which(selected_ea>n_strata[1]&selected_ea<(n_strata[1]+n_strata[2]+1))]-n_strata[1]
##for stype3
selected_3=selected_ea[which(selected_ea>(n_strata[1]+n_strata[2])&selected_ea<(n_strata[1]+n_strata[2]+n_strata[3]+1))]-(n_strata[1]+n_strata[2])
##for stype4
selected_4=selected_ea[which(selected_ea>(n_strata[1]+n_strata[2]+n_strata[3])&selected_ea<(n_strata[1]+n_strata[2]+n_strata[3]+n_strata[4]+1))]-(n_strata[1]+n_strata[2]+n_strata[3])
##for stype5
selected_5=selected_ea[which(selected_ea>(n_strata[1]+n_strata[2]+n_strata[3]+n_strata[4])&selected_ea<(n_strata[1]+n_strata[2]+n_strata[3]+n_strata[4]+n_strata[5]+1))]-(n_strata[1]+n_strata[2]+n_strata[3]+n_strata[4])
selected_num=list(selected_1,selected_2,selected_3,selected_4,selected_5)

selected_data=finite_pop[which((finite_pop$stype==1 & finite_pop$enumeration %in% selected_1)|(finite_pop$stype==2 & finite_pop$enumeration %in% selected_2)|(finite_pop$stype==3 & finite_pop$enumeration %in% selected_3)|(finite_pop$stype==4 & finite_pop$enumeration %in% selected_4)|(finite_pop$stype==5 & finite_pop$enumeration %in% selected_5)),]

## For each selected EA, select 20 HHs using simple random sampling
i=1
j=1
selected_data_2=NULL
for (i in 1:5) {
  selected_id=selected_num[[i]]
  for (j in 1:length(selected_id)) {
    set.seed(1)
    selected_house=sample(unique(finite_pop[which(finite_pop$stype==i & finite_pop$enumeration==selected_id[j]),]$household),20)
    selected_data_2=rbind(selected_data_2,finite_pop[which(finite_pop$stype==i & finite_pop$enumeration==selected_id[j] & finite_pop$household %in% selected_house),])
  }
}

set.seed(1)
response=round(runif(sum(n),0.75,0.9),2) %>% 
  as.data.frame() %>% 
  mutate(
    stype=c(rep(1,n[1]),rep(2,n[2]),rep(3,n[3]),rep(4,n[4]),rep(5,n[5])),
    enumeration=c(selected_1,selected_2,selected_3,selected_4,selected_5)
  )
colnames(response)=c("response","stype","enumeration")

data_1=unique(selected_data_2[,2:4])

set.seed(1)
data_2=left_join(data_1,response,by=c("stype","enumeration")) %>% 
  mutate(
    response_household= rbinom(nrow(data_1),1,response)
  )

set.seed(1)
selected_data_3=inner_join(selected_data_2,data_2,by=c("stype","enumeration","household"))


selected_data_4=selected_data_3 %>% 
  mutate(
    z_2=3-0.8*x_1+3.8*x_3+3*x_5+2.3*z_3-0.5*z_5-3*z_4,
    pr_2=(1/(1+exp(-z_2)))*response_household,
    response_indiv= rbinom(nrow(selected_data_3),1,pr_2) 
  )

nrow(selected_data_4[which(selected_data_4$response_household==1 & selected_data_4$response_indiv==1),])/nrow(selected_data_4[which(selected_data_4$response_household==1),])

selected_data_4[which(selected_data_4$response_indiv==0 | selected_data_4$response_household==0),25]=NA



write.csv(selected_data_4,"selected_data")
```

##Select a sub-cohort from the sample

```{r}
selected_data_5=drop_na(selected_data_4)
unique(selected_data_5[which(selected_data_5$stype==1 & selected_data_5$enumeration==selected_num[[1]][1]),]$household)


## For each selected EA, select 20 HHs using simple random sampling
i=1
j=1
data_3=NULL
for (i in 1:5) {
  selected_id=selected_num[[i]]
  for (j in 1:length(selected_id)) {
    set.seed(1)
    selected_house=sample(unique(selected_data_5[which(selected_data_5$stype==i & selected_data_5$enumeration==selected_id[j]),]$household),length(unique(selected_data_5[which(selected_data_5$stype==i & selected_data_5$enumeration==selected_id[j]),]$household))/2)
    data_3=rbind(data_3,selected_data_5[which(selected_data_5$stype==i & selected_data_5$enumeration==selected_id[j] & selected_data_5$household %in% selected_house),])
  }
}

set.seed(1)
response_2=round(runif(sum(n),0.85,0.95),2) %>% 
  as.data.frame() %>% 
  mutate(
    stype=c(rep(1,n[1]),rep(2,n[2]),rep(3,n[3]),rep(4,n[4]),rep(5,n[5])),
    enumeration=c(selected_1,selected_2,selected_3,selected_4,selected_5)
  )
colnames(response_2)=c("response","stype","enumeration")

data_4=unique(data_3[,2:4])

set.seed(1)
data_5=inner_join(data_4,response_2,by=c("stype","enumeration")) %>% 
  mutate(
    response_household = rbinom(nrow(data_4),1,response)
  )

data_6=inner_join(data_3[,-(27:30)],data_5,by = c("stype", "enumeration", "household"))

data_7=data_6 %>% 
  mutate(
    z_2=3+2.1*x_3+2.2*x_2+3.1*x_4-2.3*z_1-1.2*z_2-2*z_4,
    pr_2=(1/(1+exp(-z_2)))*response_household,
    response_indiv= rbinom(nrow(data_6),1,pr_2) 
  )

data_7[which(data_7$response_indiv==0 | data_7$response_household==0),25]=NA

write.csv(data_7,"selected_sub_cohort")
```

## vusulaization

```{r}
i=1
for(i in 1:strata){
  a=tail(unique(finite_pop[which(finite_pop$stype==i),2:3])$enumeration,1)
  print(a)
}

i=1
j=1
a=NULL
for (i in 1:strata) {
  for (j in 1:n_strata[i]) {
    a=c(a,tail(unique(finite_pop[which(finite_pop$stype==i & finite_pop$enumeration==j),2:4])$household,1))
  }
}

plot(density(a))

plot(density(unique(finite_pop[,c(2,3,4,17)])$num_indiv))

i=1
for(i in 1:strata){
  a=nrow(unique(selected_data_4[which(selected_data_4$stype==i),2:3]))
  print(a)
}


i=1
j=1
a=NULL
for (i in 1:strata) {
  for(j in 1:n[i]){
    a=c(a,length(unique(selected_data_4[which(selected_data_4$stype==i & selected_data_4$enumeration==selected_num[[i]][j]),4])))
  }
   
}

data_8=unique(selected_data_4[,c(2,3,4,28)])
sum(data_8[which(data_8$enumeration==2 & data_8$stype==1),]$response_household)/nrow(data_8[which(data_8$enumeration==2 & data_8$stype==1),])

i=1
j=1
a=NULL
for (i in 1:strata) {
  for(j in 1:n[i]){
    data_8=unique(selected_data_4[,c(2,3,4,28)])
    a=c(a,sum(data_8[which(data_8$enumeration==selected_num[[i]][j] & data_8$stype==i),]$response_household)/nrow(data_8[which(data_8$enumeration==selected_num[[i]][j] & data_8$stype==i),])
)
  }
}

plot(density(a))
```

